<?php

/**
 * Implements hook_permission().
 */
function actions_permissions_permission() {
  $permissions = array();
  $actions = actions_list();
  foreach ($actions as $callback => $action) {
    $permission = actions_permissions_get_perm($action['label'], $callback);
    $permissions[$permission] = array(
      'title' => t('Execute %label', array('%label' => $action['label'])),
      'description' => t('Execute action %label (!callback).', array('%label' => $action['label'], '!callback' => $callback)),
    );
  }
  return $permissions;
}

/**
 * Returns the permission name used in user_access().
 */
function actions_permissions_get_perm($label, $callback) {
  return "execute $callback";
}
